global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spm-api
    static_configs:
      - targets: ["spm-api:8092"]
    metrics_path: /metrics

  - job_name: spm-aggregator
    static_configs:
      - targets: ["spm-aggregator:9091"]
    metrics_path: /metrics
