apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy

  - name: SPM-DB
    type: postgres
    url: spm-db:5432
    database: spm
    user: spm_rw
    secureJsonData:
      password: spmpass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
